apiVersion: v1
kind: Service
metadata:
  name: telegram-bot-service
spec:
  selector:
    app: telegram-bot
  type: NodePort
  ports:
    - protocol: TCP
      port: 10000
      targetPort: 10000
      nodePort: 30080
